# Generated by Django 4.2.4 on 2023-08-21 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airport",
            old_name="closest_bit_city",
            new_name="closest_big_city",
        ),
    ]
