# Generated by Django 4.2.4 on 2023-08-23 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("flight", "row", "seat")},
        ),
    ]
